name: Release

# Controls when the workflow will run
on:
  push:
    tags: ["**"]

env:
  CI: false #Without this, the build will fail. As Warnings in React will be treated as errors.
  version: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      #Prep the codebase
      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: ./package.json

      - run: npm i
      - run: npm install -g vsce

      - run: npm run compile

      - run: vsce package

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
