name: Release

# Controls when the workflow will run
on:
  push:
    branches: ['**']

env:
  CI: false #Without this, the build will fail. As Warnings in React will be treated as errors.
  version: 0.${{ github.run_number }}.${{ github.run_attempt }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      #Prep the codebase
      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: ./package.json

      - run: npm i
      - run: npm install -g vsce

      - run: vsce package

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./*.vsix
